version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "04:00"
  open-pull-requests-limit: 10
  assignees:
  - cimasim89
  ignore:
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: eslint-plugin-promise
    versions:
    - 4.2.1
  - dependency-name: handlebars
    versions:
    - 4.7.6
